CREATE DATABASE BITSBOOKS;

CREATE TABLE AUTHOR(
AUTH_ID        INT        NOT NULL,
FNAME                VARCHAR(30)        NOT NULL,
LNAME                VARCHAR(30)        NOT NULL,
BIO        VARCHAR(50),
PRIMARY KEY(AUTH_ID));

CREATE TABLE ADDRESS(
ADDRESS_ID		INT				NOT NULL,
STREET        VARCHAR(30)        NOT NULL,
CITY        VARCHAR(15)        NOT NULL,
STATE        VARCHAR(12)        NOT NULL,
ZIP				INT				NOT NULL,
PRIMARY KEY(ADDRESS_ID));

CREATE TABLE PUBLISHER(
PUB_ID		INT		NOT NULL,
EMAIL                VARCHAR(30),
PHONE                CHAR(11)         NOT NULL,
CO_NAME                VARCHAR(30)        NOT NULL,
PRIMARY KEY(PUB_ID));

CREATE TABLE WAREHOUSE(
WAREHOUSE_NUM        INT         NOT NULL,
ADDRESS_ID        INT        NOT NULL,
PRIMARY KEY(WAREHOUSE_NUM),
FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) ON DELETE CASCADE);

CREATE TABLE CUSTOMER(
CUST_ID        INT         NOT NULL,
FNAME                VARCHAR(30)        NOT NULL,
LNAME                VARCHAR(30)        NOT NULL,
ADDRESS_ID        INT        NOT NULL,
EMAIL			VARCHAR(30)		NOT NULL,
PRIMARY KEY(CUST_ID),
FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) ON DELETE CASCADE);

CREATE TABLE PAYMENT_INFO(
PAYMENT_INFO	VARCHAR(19)		NOT NULL,
CUST_ID        INT        NOT NULL,
PRIMARY KEY(PAYMENT_INFO),
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON DELETE CASCADE);

CREATE TABLE BOOK(
ISBN        INT        NOT NULL,
YEAR 		INT 				NOT NULL,
TITLE        VARCHAR(50)        NOT NULL,
PRICE        INT        NOT NULL,
RATING        INT        NOT NULL,
STOCK        INT        NOT NULL,
PUB_DATE        DATE        NOT NULL,
PUB_ID        INT        NOT NULL,
CATEGORY        VARCHAR(30)        NOT NULL,
PRIMARY KEY(ISBN),
FOREIGN KEY (PUB_ID) REFERENCES PUBLISHER(PUB_ID) ON DELETE CASCADE);

CREATE TABLE ORDERS(
ORDER_NUM        INT         NOT NULL,
DATE_BOUGHT        DATE        NOT NULL,
QUANTITY        INT         NOT NULL,
ISBN			INT			NOT NULL,
CUST_ID			INT			NOT NULL,
PRIMARY KEY(ORDER_NUM, ISBN),
FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID) ON DELETE CASCADE,
FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE);

CREATE TABLE WRITTEN_BY(
AUTH_ID        INT        NOT NULL,
ISBN        INT        NOT NULL,
PRIMARY KEY(ISBN, AUTH_ID),
FOREIGN KEY (AUTH_ID) REFERENCES AUTHOR(AUTH_ID) ON DELETE CASCADE,
FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE);

CREATE TABLE EMPLOYEE(
SSN        INT         NOT NULL,
FNAME                VARCHAR(30)        NOT NULL,
LNAME                VARCHAR(30)        NOT NULL,
SALARY                INT         NOT NULL,
WAREHOUSE_NUM        INT         NOT NULL,
ADDRESS_ID        INT        NOT NULL,
PRIMARY KEY(SSN),
FOREIGN KEY (WAREHOUSE_NUM) REFERENCES WAREHOUSE(WAREHOUSE_NUM) ON DELETE CASCADE,
FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) ON DELETE CASCADE);

CREATE TABLE ADMINISTRATOR(
SALARY                INT         NOT NULL,
FNAME                VARCHAR(30)        NOT NULL,
LNAME                VARCHAR(30)        NOT NULL,
SSN        INT         NOT NULL,
FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE);

CREATE TABLE STORED_IN(
ISBN        INT         NOT NULL,
WAREHOUSE_NUM        INT         NOT NULL,
PRIMARY KEY(ISBN, WAREHOUSE_NUM),
FOREIGN KEY (WAREHOUSE_NUM) REFERENCES WAREHOUSE(WAREHOUSE_NUM) ON DELETE CASCADE,
FOREIGN KEY (ISBN) REFERENCES BOOK(ISBN) ON DELETE CASCADE);
